### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by wizeman** [janestreet/stdio#3]
Is there documentation for this library published anywhere?

**Comment by yminsky** [comment]
https://ocaml.janestreet.com/ocaml-core/latest/doc/stdio/index.html

**Comment by wizeman** [comment]
Should the link be added to the README? I couldn't find the documentation otherwise (with a DuckDuckGo search, for instance).

Thanks!

**Comment by seliopou** [comment]
This will be added to the README shortly.

**Comment by xclerc** [comment]
Fixed by https://github.com/janestreet/stdio/commit/fb42c875689f29d265082968a64bd670af2a14ae.
