### ISSUE TITLE
Error in comment around the `close` function

### ISSUE THREAD

**Issue by wizeman** [janestreet/stdio#4]
This comment seems to have a technical error:

https://github.com/janestreet/stdio/blob/12b39de053a6a595f27aaa6298a1eac705eaaf63/src/out_channel.mli#L49-L55

It says `we should probably just catch EINTR and re-attempt the close`, which is something that I think you should not do. The comment also says `This should really be fixed in the OCaml library C code, having it restart the close() syscall on EINTR.  I put a couple CRs in [fixed_close_channel], our rework of OCaml's [caml_ml_close_channel],`, which scares me a bit because that behavior seems broken, although I don't even know where that code is.

If you read `man 2 close` closely (like the full comment suggests), it says that the POSIX specification is buggy and that on many implementations (including Linux, probably the BSDs as well), `close()` is guaranteed to close the file descriptor even if there was an error (including `EINTR`), which means it should not be called again because that would lead to another error (and it can even lead to closing the wrong file descriptor if an unrelated C pthread opened another file descriptor in the mean time!).

Also, on this line:
https://github.com/janestreet/stdio/blob/12b39de053a6a595f27aaa6298a1eac705eaaf63/src/out_channel.mli#L57

... it says `EIO: I don't recall seeing this.  I think it's rare.`.
The `EIO` is only rare in the sense that storage devices don't have I/O issues most of the time. But if your storage devices are experiencing I/O errors, you will get EIO errors from the operating system, possibly during the `close()` call.

Note that the operating system may not report the `EIO` error during the `write()` call (or any other call that modifies the filesystem) because filesystem modifications are almost always buffered by the OS kernel itself. This means that the I/O error usually does not happen during the `write()` call itself, because the actual I/O write to the storage device happens seconds later, when the kernel buffers are flushed to storage, which is when the storage device reports the error to the kernel.

So if the OS detects that the error happened after the `write()` but before the `close()`, it will usually try to notify userspace by returning `EIO` on `close()` (however, even this is not guaranteed to happen, because the `close()` call may also complete before the modifications are actually written to storage by the kernel!).

Anyway, these comments are also present on Core (or is it Core_kernel?) and it has scared me into not using janestreet code for I/O, because there seemed to be a lack of deep understanding of how I/O works at the operating system level.

I've noticed that despite the comments, the code in this library is simply calling OCaml's `close`, so I think the code is actually fine in stdio (despite the comment).
I just checked Core_kernel and I found this commit from 2014 which seems to indicate that since that commit, Core_kernel's `close` probably uses OCaml's `close` rather than the broken `fixed_close_channel`:
https://github.com/janestreet/core_kernel/commit/470bf432fb26a2260d8ab033e7f3ea476cf9ceb0

... although I've tried searching and I have no idea where the In_channel/Out_channel module code actually is in Core_kernel. Anyway, Core_kernel's documentation still has that comment, so it should be fixed there as well.

Finally, thanks for releasing base and stdio, these are the first janestreet libraries that I've seriously considered using and I'm enjoying them so far!

**Comment by ghost** [comment]
I agree that this comment is a bit misleading. However, don't forget that the manual page will be different on different systems. In fact, we looked at the man page for `close` on a couple of machines and saw nothing about `EINTR`. We only saw it mentioned [here](http://man7.org/linux/man-pages/man2/close.2.html). So the best we can say it that `close` may raise unix errors such as `EINTR` or `EIO` and that in such cases the file descriptor may or may not have been closed, depending on the system.

**Comment by wizeman** [comment]
Hi @diml,

Yes, that would be great. It would be much better than the current comment, which could mislead someone into re-attempting to call `close()` after an `EINTR`, when it might not be safe to do so (on multi-threaded Linux programs, for instance).

Thanks!

**Comment by ghost** [comment]
Sorry, this fell off my radar.

I remember discussing this with other JS developers, but I forgot what we concluded. I also don't have quite enough time to look at this again, so I'm closing this issue. @wizeman, you should feel free to submit a PR to update the documentation though.
